arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: lib/l10n/untranslated.json
header: |
  // SPDX-FileCopyrightText: © 2026 Alexandre Leclerc
  //
  // SPDX-License-Identifier: MPL-2.0
